package frontend

// embed_ui2.go embeds the new Vue 3 / Vite frontend (UI2) served at /ui2.
// It is intentionally separate from embed.go so the legacy www/ embed stays
// zero-diff. The build output lives in ui2/dist/ and is regenerated by
// `npm run build` (locally) or the Dockerfile frontend-builder stage (CI);
// a tracked placeholder ui2/dist/index.html guarantees this embed never fails
// on a clean checkout that hasn't run npm.

import (
	"embed"
	"io/fs"
	"net/http"
)

//go:embed all:ui2/dist
var ui2Assets embed.FS

// UI2FS returns an http.FileSystem rooted at the embedded ui2/dist directory.
// The "ui2/dist/" prefix is stripped so files are served at their natural
// paths (e.g. "ui2/dist/assets/index.js" → "/assets/index.js" under /ui2).
func UI2FS() http.FileSystem {
	sub, err := fs.Sub(ui2Assets, "ui2/dist")
	if err != nil {
		// Should never happen: "ui2/dist" is always present (embed directive
		// + tracked placeholder index.html).
		panic("frontend: failed to sub embedded UI2 FS: " + err.Error())
	}
	return http.FS(sub)
}
