#!/usr/bin/env bash
# =============================================================================
# Cascade — Full deployment script
# Ubuntu 22.04 / 24.04, run as root
# Usage:  bash deploy/setup.sh
#         bash deploy/setup.sh --yes   # non-interactive (reads all from .env)
# =============================================================================
set -euo pipefail

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
CADDY_DIR="$SCRIPT_DIR/caddy"
CERT_DIR="/etc/ssl/cascade"
REBOOT_FLAG="/var/lib/.cascade-needs-reboot"

# ── Colors ───────────────────────────────────────────────────────────────────
G='\033[0;32m'; Y='\033[1;33m'; R='\033[0;31m'; B='\033[0;34m'; N='\033[0m'

# ── Docker Compose command (v2 plugin or v1 standalone) ───────────────────────
# Resolved after Docker is confirmed installed (Step 3).
# Use COMPOSE_CMD everywhere instead of hardcoded "docker compose".
resolve_compose() {
  if docker compose version &>/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
  elif command -v docker-compose &>/dev/null; then
    COMPOSE_CMD="docker-compose"
  else
    fail "docker compose not found. Install docker-compose-plugin: apt install docker-compose-plugin"
  fi
  ok "Compose: $COMPOSE_CMD"
}
COMPOSE_CMD="docker compose"  # default, overridden by resolve_compose after Step 3

ok()   { echo -e "${G}  [✓]${N} $*"; }
info() { echo -e "${B}  [→]${N} $*"; }
warn() { echo -e "${Y}  [!]${N} $*"; }
fail() { echo -e "${R}  [✗]${N} $*"; exit 1; }

# ── Parse args ───────────────────────────────────────────────────────────────
YES=0
for arg in "$@"; do [[ "$arg" == "--yes" ]] && YES=1; done

# ── Load .env ────────────────────────────────────────────────────────────────
[[ -f "$ENV_FILE" ]] && source "$ENV_FILE"

# ── Helpers ──────────────────────────────────────────────────────────────────
ask() {
  # ask VAR "Prompt" [default]
  local var="$1" prompt="$2" default="${3:-}"
  local current="${!var:-}"
  [[ -n "$current" ]] && { ok "$prompt: (loaded from .env: $current)"; return; }
  if [[ $YES -eq 1 ]]; then
    [[ -n "$default" ]] && eval "$var='$default'" && return
    fail "$prompt is required — set in $ENV_FILE"
  fi
  local hint=""; [[ -n "$default" ]] && hint=" [$default]"
  read -rp "  $prompt$hint: " val
  eval "$var='${val:-$default}'"
}

save_env() {
  # Rewrite .env with current values (no plaintext passwords).
  # WG_QUICK_USERSPACE_IMPLEMENTATION is written directly so docker-compose
  # env_file can inject it into the container without host-side interpolation.
  local userspace_val=""
  [[ "${AWG_USERSPACE_IMPL:-}" == "amneziawg-go" ]] && userspace_val="amneziawg-go"
  cat > "$ENV_FILE" << EOF
# Cascade deploy config — generated by setup.sh
# All values here are injected into the container via env_file.
# Do NOT edit docker-compose.go.yml — put overrides here instead.
WG_HOST=${WG_HOST:-}
ADMIN_PATH=${ADMIN_PATH:-}
ACME_EMAIL=${ACME_EMAIL:-}
PORT=${CASCADE_PORT:-8888}
BIND_ADDR=${BIND_ADDR:-127.0.0.1}
PASSWORD_HASH=
AWG_USERSPACE_IMPL=${AWG_USERSPACE_IMPL:-}
WG_QUICK_USERSPACE_IMPLEMENTATION=${userspace_val}
EOF
  chmod 600 "$ENV_FILE"
}

is_ip() { [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; }

detect_ip() {
  local ip
  ip=$(curl -s --max-time 5 https://ifconfig.me 2>/dev/null) && [[ -n "$ip" ]] && echo "$ip" && return
  ip=$(ip route get 8.8.8.8 2>/dev/null | awk '/src/{print $7}') && [[ -n "$ip" ]] && echo "$ip" && return
  echo ""
}

# ── Must run as root ──────────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && fail "Run as root (sudo bash deploy/setup.sh)"

# ── Banner ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${B}╔══════════════════════════════════════╗${N}"
echo -e "${B}║       Cascade — Deploy Setup         ║${N}"
echo -e "${B}╚══════════════════════════════════════╝${N}"
echo ""

# ── Detect OS ─────────────────────────────────────────────────────────────────
OS_ID=$(grep '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
OS_VER=$(grep '^VERSION_ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
KERNEL_MAJOR=$(uname -r | cut -d. -f1)

[[ "$OS_ID" != "ubuntu" ]] && warn "Detected OS: $OS_ID $OS_VER (tested on Ubuntu 22.04 / 24.04 only)"
info "OS: Ubuntu $OS_VER  |  Kernel: $(uname -r)"

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 0 — Swap (1 GB)
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 0: Swap${N}"

SWAPFILE=/swapfile
if swapon --show | grep -q "$SWAPFILE"; then
  ok "Swap already active ($SWAPFILE)"
elif [[ -f "$SWAPFILE" ]]; then
  info "Swap file exists but not active — activating..."
  chmod 600 "$SWAPFILE"
  mkswap "$SWAPFILE" > /dev/null
  swapon "$SWAPFILE"
  ok "Swap activated ($(du -h "$SWAPFILE" | cut -f1))"
else
  info "Creating 1 GB swap at $SWAPFILE..."
  fallocate -l 1G "$SWAPFILE" 2>/dev/null || dd if=/dev/zero of="$SWAPFILE" bs=1M count=1024 status=none
  chmod 600 "$SWAPFILE"
  mkswap "$SWAPFILE" > /dev/null
  swapon "$SWAPFILE"
  ok "Swap created and activated (1 GB)"
fi

# Persist across reboots
if ! grep -q "$SWAPFILE" /etc/fstab; then
  echo "$SWAPFILE none swap sw 0 0" >> /etc/fstab
  ok "Added $SWAPFILE to /etc/fstab"
fi

# Tune swappiness: use swap only under real memory pressure
sysctl -w vm.swappiness=10 > /dev/null
if ! grep -q 'vm.swappiness' /etc/sysctl.d/99-cascade.conf 2>/dev/null; then
  echo 'vm.swappiness=10' >> /etc/sysctl.d/99-cascade.conf
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 1 — Kernel upgrade (Ubuntu 22.04 only)
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 1: Kernel${N}"

if [[ "$OS_VER" == "22.04" && "$KERNEL_MAJOR" -lt 6 ]]; then
  if [[ -f "$REBOOT_FLAG" ]]; then
    fail "Reboot flag found but kernel is still $KERNEL_MAJOR.x — did you reboot? Remove $REBOOT_FLAG and rerun after rebooting."
  fi
  info "Ubuntu 22.04 with kernel $KERNEL_MAJOR.x — upgrading to HWE 6.x..."
  apt-get update -qq
  apt-get install -y linux-generic-hwe-22.04
  touch "$REBOOT_FLAG"
  echo ""
  echo -e "${Y}  ┌─────────────────────────────────────────────────┐${N}"
  echo -e "${Y}  │  Kernel upgraded. REBOOT REQUIRED.              │${N}"
  echo -e "${Y}  │  After reboot, run:  bash deploy/setup.sh       │${N}"
  echo -e "${Y}  └─────────────────────────────────────────────────┘${N}"
  echo ""
  exit 0
else
  [[ -f "$REBOOT_FLAG" ]] && rm -f "$REBOOT_FLAG"
  ok "Kernel $(uname -r) — OK"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 2 — AmneziaWG run mode (userspace vs kernel)
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 2: AmneziaWG run mode${N}"

# ── Helpers for applying run mode ────────────────────────────────────────────
apply_userspace_mode() {
  # Unload kernel module if loaded — amneziawg-go defers to kernel when present
  if lsmod | grep -q amneziawg; then
    info "Unloading amneziawg kernel module (userspace mode selected)..."
    modprobe -r amneziawg 2>/dev/null || warn "Could not unload amneziawg — reboot required"
  fi
  echo "blacklist amneziawg" > /etc/modprobe.d/amneziawg-blacklist.conf
  rm -f /etc/modules-load.d/amneziawg.conf
  ok "Kernel module unloaded and blacklisted"
}

apply_kernel_mode() {
  # Remove blacklist (if switching from userspace)
  rm -f /etc/modprobe.d/amneziawg-blacklist.conf
  if lsmod | grep -q amneziawg; then
    ok "amneziawg already loaded"
  elif dpkg -l amneziawg &>/dev/null 2>&1; then
    # Package installed but not loaded — just modprobe
    info "Loading amneziawg kernel module..."
    modprobe amneziawg
    echo "amneziawg" > /etc/modules-load.d/amneziawg.conf
    ok "amneziawg loaded"
  else
    # Not installed at all — full PPA install
    info "Installing AmneziaWG kernel module (ppa:amnezia/ppa)..."
    add-apt-repository -y ppa:amnezia/ppa > /dev/null 2>&1
    apt-get update -qq
    apt-get install -y amneziawg
    modprobe amneziawg
    echo "amneziawg" > /etc/modules-load.d/amneziawg.conf
    ok "amneziawg installed and loaded"
  fi
}

# Load saved mode from .env if present, otherwise ask
if [[ "${AWG_USERSPACE_IMPL:-unset}" != "unset" ]]; then
  if [[ "$AWG_USERSPACE_IMPL" == "amneziawg-go" ]]; then
    echo -e "  Current mode: ${G}Userspace (amneziawg-go)${N}"
  else
    echo -e "  Current mode: ${Y}Kernel module${N}"
  fi
  echo ""
  if [[ $YES -eq 1 ]]; then
    CHANGE_MODE="n"
  else
    read -rp "  Change run mode? [y/N]: " CHANGE_MODE
    CHANGE_MODE="${CHANGE_MODE:-n}"
  fi

  if [[ "${CHANGE_MODE,,}" == "y" ]]; then
    # Re-ask the choice
    AWG_USERSPACE_IMPL=""
  fi
fi

if [[ "${AWG_USERSPACE_IMPL:-unset}" != "unset" ]]; then
  # Mode confirmed, apply it
  if [[ "$AWG_USERSPACE_IMPL" == "amneziawg-go" ]]; then
    ok "Run mode: Userspace"
    apply_userspace_mode
  else
    ok "Run mode: Kernel module"
    apply_kernel_mode
  fi
else
  echo ""
  echo -e "  ${B}Choose AmneziaWG run mode:${N}"
  echo -e "  ${G}[1] Userspace${N} (recommended)"
  echo -e "      • No kernel module required — works on any VPS"
  echo -e "      • No reboot needed, even on Ubuntu 22.04"
  echo -e "      • Stable — no deadlocks"
  echo -e "      • Performance: ~70% of kernel (sufficient for VPN routing)"
  echo ""
  echo -e "  ${Y}[2] Kernel module${N}"
  echo -e "      • Maximum performance"
  echo -e "      • Requires PPA install + reboot on Ubuntu 22.04"
  echo -e "      • Known deadlock issues in AWG kernel module"
  echo ""
  if [[ $YES -eq 1 ]]; then
    AWG_MODE_CHOICE="1"
  else
    read -rp "  Choice [1]: " AWG_MODE_CHOICE
    AWG_MODE_CHOICE="${AWG_MODE_CHOICE:-1}"
  fi

  if [[ "$AWG_MODE_CHOICE" == "2" ]]; then
    AWG_USERSPACE_IMPL="kernel"
    ok "Run mode: Kernel module"
    apply_kernel_mode
  else
    AWG_USERSPACE_IMPL="amneziawg-go"
    ok "Run mode: Userspace (amneziawg-go)"
    apply_userspace_mode
  fi
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 3 — Docker
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 3: Docker${N}"

if command -v docker &>/dev/null; then
  DOCKER_VER=$(docker --version | awk '{print $3}' | tr -d ,)
  ok "Docker ${DOCKER_VER} already installed"

  # Detect Ubuntu-bundled docker.io (old, ships docker-compose 1.29 which breaks on
  # Docker 25+ image format — missing ContainerConfig). Replace with official Docker CE.
  if dpkg -l docker.io 2>/dev/null | grep -q '^ii'; then
    warn "Detected Ubuntu-bundled docker.io — replacing with official Docker CE..."
    apt-get remove -y docker.io docker-compose 2>/dev/null || true
    curl -fsSL https://get.docker.com | sh
    ok "Replaced docker.io with official Docker CE $(docker --version | awk '{print $3}' | tr -d ,)"
  fi
else
  info "Installing Docker (official)..."
  curl -fsSL https://get.docker.com | sh
  ok "Docker installed: $(docker --version | awk '{print $3}' | tr -d ,)"
fi

resolve_compose


# ═══════════════════════════════════════════════════════════════════════════════
# STEP 4 — sysctl
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 4: Kernel parameters${N}"

SYSCTL_FILE="/etc/sysctl.d/99-cascade.conf"
if [[ -f "$SYSCTL_FILE" ]]; then
  ok "sysctl config already present"
else
  cat > "$SYSCTL_FILE" << 'SYSCTL'
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.core.rmem_max = 7340032
net.core.wmem_max = 7340032
SYSCTL
  sysctl --system -q
  ok "sysctl applied (ip_forward, UDP buffers)"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 5a — Generate decoy video (QUIC streaming bait)
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 5a: Decoy video${N}"

VIDEO_DIR="$CADDY_DIR/www/video"
VIDEO_FILE="$VIDEO_DIR/decoy.mp4"
mkdir -p "$VIDEO_DIR"

if [[ -f "$VIDEO_FILE" ]]; then
  ok "decoy.mp4 already exists ($(du -sh "$VIDEO_FILE" | cut -f1))"
else
  if ! command -v ffmpeg &>/dev/null; then
    info "Installing ffmpeg..."
    apt-get install -y ffmpeg -qq
    ok "ffmpeg installed"
  fi

  # 480p noise video: easier to encode than 720p, still convincing as streaming.
  # noise=c0s=18 = TV-static intensity. ultrafast preset = CPU-friendly.
  # b:v 2000k → ~15 MB for 60s → browser re-fetches every loop = ~2 Mbps QUIC stream.
  # faststart = moov atom at front → playback starts before full download.
  info "Generating decoy.mp4 (480p noise, 60s — may take 1-2 min on slow CPUs)..."
  ffmpeg -y \
    -f lavfi -i "color=c=0x0f0f13:s=854x480:r=24" \
    -vf "noise=c0s=18:c0f=t,hue=s=0.1" \
    -t 60 \
    -c:v libx264 -b:v 2000k -preset ultrafast \
    -an \
    -movflags +faststart \
    "$VIDEO_FILE" > /tmp/cascade-ffmpeg.log 2>&1 &
  FFMPEG_PID=$!
  # Spinner so terminal doesn't look frozen
  SPIN='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'; si=0
  while kill -0 "$FFMPEG_PID" 2>/dev/null; do
    si=$(( (si+1) % 10 ))
    printf "\r    ${SPIN:$si:1} encoding..."
    sleep 0.3
  done
  printf "\r"
  if wait "$FFMPEG_PID"; then
    ok "decoy.mp4 generated ($(du -sh "$VIDEO_FILE" | cut -f1), 60s, ~2 Mbps)"
  else
    warn "ffmpeg failed — decoy video skipped (log: /tmp/cascade-ffmpeg.log)"
    warn "Canvas noise fallback will be used instead"
  fi
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 5 — Build Cascade
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 5: Build Cascade${N}"

cd "$REPO_DIR"

BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
if [[ "$BRANCH" != "feature/go-rewrite" ]]; then
  warn "Current branch: $BRANCH (expected feature/go-rewrite)"
fi

info "Pulling latest changes..."
git pull origin "$BRANCH" 2>&1 | tail -1

if docker image inspect cascade:latest &>/dev/null; then
  ok "Image cascade:latest already built"
  if [[ $YES -eq 0 ]]; then
    read -rp "  Rebuild? [y/N]: " REBUILD
    [[ "${REBUILD,,}" == "y" ]] && bash build-go.sh
  fi
else
  info "Building Docker image..."
  bash build-go.sh
  ok "Image built"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 6 — Collect configuration
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 6: Configuration${N}"

# WG_HOST
if [[ -z "${WG_HOST:-}" ]]; then
  DETECTED_IP=$(detect_ip)
  if [[ $YES -eq 1 ]]; then
    WG_HOST="${DETECTED_IP}"
  else
    read -rp "  Server public IP or domain [${DETECTED_IP}]: " WG_HOST_INPUT
    WG_HOST="${WG_HOST_INPUT:-$DETECTED_IP}"
  fi
fi
ok "WG_HOST = $WG_HOST"

# ADMIN_PATH
if [[ -z "${ADMIN_PATH:-}" ]]; then
  ADMIN_PATH=$(openssl rand -hex 16)
  info "Generated ADMIN_PATH: $ADMIN_PATH"
fi
ok "ADMIN_PATH = $ADMIN_PATH"

# ACME_EMAIL (optional)
if [[ -z "${ACME_EMAIL:-}" && $YES -eq 0 ]]; then
  read -rp "  Email for TLS certificate (optional, press Enter to skip): " ACME_EMAIL
fi

# Ports
CASCADE_PORT="${CASCADE_PORT:-8888}"
BIND_ADDR="${BIND_ADDR:-127.0.0.1}"

# Save all non-secret values
save_env
ok "Config saved to $ENV_FILE"

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 7 — Start Cascade
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 7: Cascade${N}"

# All config (WG_HOST, PORT, BIND_ADDR, WG_QUICK_USERSPACE_IMPLEMENTATION) is in
# deploy/.env — injected via env_file. No sed patching of docker-compose needed.
COMPOSE_FILE="$REPO_DIR/docker-compose.go.yml"

info "Starting Cascade..."
$COMPOSE_CMD -f "$COMPOSE_FILE" down 2>/dev/null || true
$COMPOSE_CMD -f "$COMPOSE_FILE" up -d

# Wait for health
info "Waiting for health check..."
for i in $(seq 1 90); do
  STATUS=$(curl -s --max-time 2 "http://127.0.0.1:${CASCADE_PORT}/api/health" 2>/dev/null | grep -o '"ok"' || true)
  if [[ "$STATUS" == '"ok"' ]]; then
    ok "Cascade healthy on 127.0.0.1:${CASCADE_PORT}"
    break
  fi
  sleep 1
  [[ $i -eq 90 ]] && fail "Cascade did not become healthy after 90s — check: docker logs cascade"
done

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 8 — TLS certificate
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 8: TLS certificate (acme.sh)${N}"

mkdir -p "$CERT_DIR"

# Install acme.sh if needed
if [[ ! -f "$HOME/.acme.sh/acme.sh" ]]; then
  info "Installing acme.sh..."
  EMAIL_ARG=""
  [[ -n "${ACME_EMAIL:-}" ]] && EMAIL_ARG="email=${ACME_EMAIL}"
  curl -fsSL https://get.acme.sh | sh -s $EMAIL_ARG
  ok "acme.sh installed"
else
  ok "acme.sh already installed"
fi

ACME="$HOME/.acme.sh/acme.sh"

# Check if cert already exists and is valid
if [[ -f "$CERT_DIR/server.crt" ]]; then
  EXPIRY=$(openssl x509 -in "$CERT_DIR/server.crt" -noout -enddate 2>/dev/null | cut -d= -f2 || true)
  ok "Certificate already present (expires: $EXPIRY)"
  info "Skipping issuance — to reissue: $ACME --issue --force ..."
else
  info "Issuing TLS certificate for: $WG_HOST"

  # Port 80 must be free for standalone mode
  if ss -tlnp 2>/dev/null | grep -q ':80 '; then
    warn "Port 80 is already in use — attempting webroot mode via /srv/acme"
    mkdir -p /srv/acme
    "$ACME" --issue --server letsencrypt \
      -d "$WG_HOST" --webroot /srv/acme \
      $(is_ip "$WG_HOST" && echo "--certificate-profile shortlived --days 3" || true)
  else
    "$ACME" --issue --server letsencrypt \
      -d "$WG_HOST" --standalone \
      $(is_ip "$WG_HOST" && echo "--certificate-profile shortlived --days 3" || true)
  fi

  "$ACME" --install-cert -d "$WG_HOST" \
    --key-file       "$CERT_DIR/server.key" \
    --fullchain-file "$CERT_DIR/server.crt" \
    --reloadcmd      "docker exec cascade-caddy caddy reload --config /etc/caddy/Caddyfile 2>/dev/null || true"

  ok "Certificate installed to $CERT_DIR"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 9 — Caddy reverse proxy
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 9: Caddy reverse proxy${N}"

# Write Caddy .env
cat > "$CADDY_DIR/.env" << EOF
ADMIN_PATH=${ADMIN_PATH}
CASCADE_PORT=${CASCADE_PORT}
EOF
chmod 600 "$CADDY_DIR/.env"

info "Starting Caddy..."
cd "$CADDY_DIR"
$COMPOSE_CMD down 2>/dev/null || true
$COMPOSE_CMD up -d --build

# Wait for Caddy
sleep 2
if docker ps --filter "name=cascade-caddy" --filter "status=running" | grep -q cascade-caddy; then
  ok "Caddy running"
else
  fail "Caddy failed to start — check: $COMPOSE_CMD -f deploy/caddy/docker-compose.yml logs"

fi

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 10 — Verify
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${B}── Step 10: Verification${N}"

cd "$REPO_DIR"

DECOY=$(curl -sk --max-time 5 "https://${WG_HOST}/" 2>/dev/null | grep -o 'StreamVault' || true)
if [[ "$DECOY" == "StreamVault" ]]; then
  ok "Decoy site reachable (StreamVault)"
else
  warn "Decoy site check failed — may need a few seconds"
fi

ADMIN=$(curl -sk --max-time 5 "https://${WG_HOST}/${ADMIN_PATH}/api/health" 2>/dev/null | grep -o '"ok"' || true)
if [[ "$ADMIN" == '"ok"' ]]; then
  ok "Admin API reachable via Caddy"
else
  warn "Admin API check failed — check Caddy logs"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# Summary
# ═══════════════════════════════════════════════════════════════════════════════
echo ""
echo -e "${G}╔══════════════════════════════════════════════════════╗${N}"
echo -e "${G}║               Cascade — Setup Complete               ║${N}"
echo -e "${G}╚══════════════════════════════════════════════════════╝${N}"
echo ""
echo -e "  Admin URL:   ${G}https://${WG_HOST}/${ADMIN_PATH}/${N}"
echo ""
echo -e "  ${Y}First login:${N}"
echo -e "    1. Open the URL above in your browser"
echo -e "    2. You will see a ${B}Create First User${N} form (open mode)"
echo -e "    3. Create your admin account"
echo -e "    4. Enable TOTP in Settings → Users for added security"
echo ""
echo -e "  ${Y}Update:${N}"
echo -e "    git pull origin feature/go-rewrite && ./build-go.sh"
echo -e "    docker compose -f docker-compose.go.yml up -d"
echo ""
echo -e "  ${Y}Logs:${N}"
echo -e "    docker logs cascade"
echo -e "    docker compose -f deploy/caddy/docker-compose.yml logs"
echo ""
echo -e "  Config saved: ${B}${ENV_FILE}${N}"
echo ""
